### ISSUE TITLE
Makers dont rebuild

### ISSUE THREAD

**Issue by thienhaole92** [atiqsamtia/interactive_maps_marker_flutter#1]
Before I load data from server my makers list is empty after I get data from server I rebuild makers list but nothing is displayed.

final List<MarkerItem> markers = List();
build UI
then add maker item into markers list

Nothing happen. Please help me to check it

**Comment by atiqsamtia** [comment]
You need to wrap this widget inside a stateful widget and update the markers list. 

I've added an example in the example project of this repo. Do check this commit https://github.com/atiqsamtia/interactive_maps_marker_flutter/commit/d1d6ca58e6d35fde5313c8713ba0a0a9379adbc8
